use_frameworks!

platform :ios, '10.0'

target 'YJHSocketRocket_Example' do
  pod 'YJHSocketRocket', :path => '../'

  target 'YJHSocketRocket_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
